import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

import { ELEMENT_STATUSES, elementStatusPresentation } from "./elementStatus";
import { NON_REFER_REASON_TEXT, QUOTE_CHECK_TEXT } from "./reasonText";
import { REFER_REASON_TEXT, REFER_REASONS, referReasonPresentation, REFERRED_HEADING, TWO_JUDGES_ONLY_LABEL } from "./referReason";
import { classifyVerifyError } from "./citationCheck";
import { classifyAnalyseError } from "./serviceStatus";
import { streamErrorText } from "./streamError";
import { MEMO_DISCLAIMER } from "./memo";
import { CITATION_ERROR_TEXT, CODED_ERROR_TEXT, ELEMENT_STATUS_EXPLANATION, SERVICE_ERROR_TEXT, SESSION_401_TEXT } from "./signedStrings";
import { ApiError } from "./api";

// The app's reason, quote-check, status and service-error strings are the SIGNED wording, word for word. This file holds them to
// the signed sources so a drift fails here, in either direction:
//  - fixtures/reasonCodesTable.json: the engine's docs/api/reason-codes.md (15 reasons, 8 quote checks), generated by
//    scripts/gen-reason-table.py; its header carries the path, the engine sha and the file's sha256;
//  - fixtures/signedGapStrings.json: the reviewed string note for the statuses and service errors (header: source, head, sha256);
//  - fixtures/engineCodes.json and engineContractReasons.json: the engine's own code lists, copied with their source.

const read = (f: string) => JSON.parse(readFileSync(join(__dirname, "fixtures", f), "utf8"));
const TABLE = read("reasonCodesTable.json") as {
  source: { path: string; ref: string; engine_sha: string; file_sha256: string };
  reasons: Record<string, { text: string; twoJudgesOnly: boolean }>;
  quote_check: Record<string, string>;
};
const GAP = read("signedGapStrings.json") as { source: string; strings: Record<string, string> };
const APP_SIGNED = read("appSignedStrings.json") as { source: string; strings: Record<string, string> };
const CODED = read("codedErrorStrings.json") as { source: { head: string; file_sha256: string; file: string }; strings: Record<string, string> };
const AMEND = read("signedCitationAmendments.json") as { source: string; supersedes: Record<string, string>; strings: Record<string, string> };
const ENGINE = read("engineCodes.json") as {
  quote_check: string[];
  element_status: string[];
  service_error_503: string[];
  service_error_503_reason: string[];
};
const ENGINE_REASONS = read("engineContractReasons.json") as { all: string[]; refer: string[] };

/** Verbatim after whitespace normalisation only: no case folding, no punctuation changes. */
const norm = (s: string): string => s.replace(/\s+/g, " ").trim();

/**
 * Codes that are in the engine but have NO app surface yet. Named and explicit on purpose: a code is allowed here only with a
 * reason, and a later surface for it must move it out of this list (the test below fails if a listed code gains an app string).
 */
const NO_APP_SURFACE_FOLLOW_UP: Record<string, string> = {
  checker_unavailable: "signed (note head e65e5ffc) but no app surface: the admin-only Nyaya audit page shows only the HTTP status",
  registry_checker_unavailable: "signed (note head e65e5ffc) but no app surface: the admin-only Nyaya registry pages show only the HTTP status",
  vendor_not_allowed: "signed (note head e65e5ffc), coded 403 of POST /api/nyaya/ask: no app surface, the admin-only Nyaya page shows only the HTTP status",
  // The uncoded free-text 503s (agent at capacity, agent unavailable with exception text) have no code to compare yet; they
  // land here when Track C's stable codes arrive (pravrudhi #318) and get a string in a follow-up.
};

test("the signed table is the one expected: counts, and a header that names its source, engine sha and file sha256", () => {
  assert.equal(Object.keys(TABLE.reasons).length, 15);
  assert.equal(Object.keys(TABLE.quote_check).length, 8);
  assert.match(TABLE.source.engine_sha, /^[0-9a-f]{40}$/);
  assert.match(TABLE.source.file_sha256, /^[0-9a-f]{64}$/);
  assert.match(TABLE.source.path, /reason-codes\.md/);
  assert.match(GAP.source, /8757dd2b/);
  assert.match(GAP.source, /[0-9a-f]{64}/);
});

test("every REFER reason's message is the signed sentence, verbatim", () => {
  for (const r of REFER_REASONS) {
    const signed = TABLE.reasons[r];
    assert.ok(signed, `${r} is not in the signed table`);
    assert.equal(norm(referReasonPresentation(r).message), norm(signed.text), r);
    assert.equal(REFER_REASON_TEXT[r].twoJudgesOnly, signed.twoJudgesOnly, `${r}: the two-judges label`);
  }
});

test("every other reason's text and every quote check's text is the signed sentence, verbatim", () => {
  for (const [code, signed] of Object.entries(TABLE.reasons)) {
    if ((REFER_REASONS as readonly string[]).includes(code)) continue;
    assert.equal(norm(NON_REFER_REASON_TEXT[code] ?? ""), norm(signed.text), code);
  }
  for (const [code, text] of Object.entries(TABLE.quote_check)) assert.equal(norm(QUOTE_CHECK_TEXT[code] ?? ""), norm(text), code);
});

test("the table has exactly the reasons the app knows: 9 referrals + 6 others, and no extras either way", () => {
  assert.deepEqual(new Set([...REFER_REASONS, ...Object.keys(NON_REFER_REASON_TEXT)]), new Set(Object.keys(TABLE.reasons)));
  assert.deepEqual(new Set(Object.keys(QUOTE_CHECK_TEXT)), new Set(Object.keys(TABLE.quote_check)));
});

test("the gap strings (statuses and service errors) are the signed wording, verbatim", () => {
  for (const [status, text] of Object.entries(ELEMENT_STATUS_EXPLANATION)) assert.equal(norm(text), norm(GAP.strings[status]), status);
  for (const code of ["judges_offline", "judges_warming", "judge_unavailable", "outside_service_window", "service_config_missing"] as const) {
    assert.equal(norm(SERVICE_ERROR_TEXT[code]), norm(GAP.strings[code]), code);
  }
  assert.equal(norm(SERVICE_ERROR_TEXT.rate_limited), norm(GAP.strings.http_429));
  // and what the page actually shows for each element status and each coded error starts from that sentence
  for (const status of ELEMENT_STATUSES) assert.equal(elementStatusPresentation(status).explanation, ELEMENT_STATUS_EXPLANATION[status]);
  const shown = (e: ApiError) => norm(classifyAnalyseError(e).message);
  assert.equal(shown(new ApiError(503, "/x", { code: "judges_offline" })), norm(GAP.strings.judges_offline));
  assert.equal(shown(new ApiError(503, "/x", { code: "judge_unavailable" })), norm(GAP.strings.judge_unavailable));
  assert.equal(shown(new ApiError(503, "/x", { code: "outside_service_window" })), norm(GAP.strings.outside_service_window));
  assert.equal(shown(new ApiError(503, "/x", { code: "service_config_missing" })), norm(GAP.strings.service_config_missing));
  assert.ok(shown(new ApiError(503, "/x", { code: "judge_unavailable", reason: "judges_warming", retryAfter: 30 })).startsWith(norm(GAP.strings.judges_warming)));
  assert.ok(shown(new ApiError(429, "/x", { retryAfter: 12 })).startsWith(norm(GAP.strings.http_429)));
  assert.equal(shown(new ApiError(429, "/x")), norm(GAP.strings.http_429));
});

test("the referral heading is 'Referred to a lawyer'; no REFER string has a lead-in, 'second check' or 'temporarily'", () => {
  assert.equal(REFERRED_HEADING, "Referred to a lawyer");
  assert.equal(TWO_JUDGES_ONLY_LABEL, "(deployments that use two judges only)");
  for (const r of REFER_REASONS) {
    const { message } = referReasonPresentation(r);
    assert.doesNotMatch(message, /A lawyer must decide this matter:/i, r);
    assert.doesNotMatch(message, /second check|temporarily/i, r);
    assert.doesNotMatch(message, /deployments that use two judges/i, `${r}: the label is outside the sentence`);
  }
});

test("no app string source says 'second check' or 'temporarily', and none uses the 'must decide this matter' lead-in", () => {
  const files = ["referReason.ts", "reasonText.ts", "signedStrings.ts", "serviceStatus.ts", "elementStatus.ts", "memo.ts", join("..", "app", "matters", "page.tsx")];
  for (const f of files) {
    const code = readFileSync(join(__dirname, f), "utf8")
      .split("\n")
      .filter((l) => !l.trim().startsWith("//"))
      .join("\n");
    assert.doesNotMatch(code, /second check|temporarily/i, f);
    assert.doesNotMatch(code, /must decide this matter/i, f);
  }
});

test("every engine code is in the table, in the app, or in the named no-app-surface allow-list: none is missing", () => {
  const inTable = new Set([...Object.keys(TABLE.reasons), ...Object.keys(TABLE.quote_check)]);
  const inApp = new Set<string>([
    ...REFER_REASONS,
    ...Object.keys(NON_REFER_REASON_TEXT),
    ...Object.keys(QUOTE_CHECK_TEXT),
    ...ELEMENT_STATUSES,
    ...Object.keys(SERVICE_ERROR_TEXT),
    ...Object.keys(CODED_ERROR_TEXT),
    ...Object.keys(CITATION_ERROR_TEXT),
  ]);
  const covered = (code: string) => inTable.has(code) || inApp.has(code) || code in NO_APP_SURFACE_FOLLOW_UP;
  const engineCodes = [
    ...ENGINE_REASONS.all,
    ...ENGINE.quote_check,
    ...ENGINE.element_status,
    ...ENGINE.service_error_503,
    ...ENGINE.service_error_503_reason,
  ];
  const missing = engineCodes.filter((c) => !covered(c));
  assert.deepEqual(missing, [], `engine codes with no signed string, app string or allow-list entry: ${missing.join(", ")}`);
  // the app's status list is the engine's, both ways
  assert.deepEqual([...ELEMENT_STATUSES].sort(), [...ENGINE.element_status].sort());
});

test("the allow-list is honest: only engine codes, each with a reason, and none of them already has an app string", () => {
  const engine = new Set([...ENGINE.service_error_503, ...((ENGINE as { http_403_coded?: string[] }).http_403_coded ?? []), ...ENGINE_REASONS.all, ...ENGINE.quote_check, ...ENGINE.element_status]);
  const inApp = new Set<string>([...Object.keys(SERVICE_ERROR_TEXT), ...Object.keys(CODED_ERROR_TEXT), ...Object.keys(CITATION_ERROR_TEXT), ...Object.keys(NON_REFER_REASON_TEXT), ...Object.keys(QUOTE_CHECK_TEXT), ...REFER_REASONS]);
  for (const [code, why] of Object.entries(NO_APP_SURFACE_FOLLOW_UP)) {
    assert.ok(engine.has(code), `${code} is not an engine code`);
    assert.ok(why.length > 0);
    assert.ok(!inApp.has(code), `${code} now has an app string: remove it from the allow-list`);
  }
});

test("the app-specific signed strings (web session 401, memo disclaimer) are verbatim, and the 401 is what the page shows", () => {
  assert.match(APP_SIGNED.source, /R1/);
  assert.equal(norm(SESSION_401_TEXT), norm(APP_SIGNED.strings.session_401));
  assert.equal(norm(MEMO_DISCLAIMER), norm(APP_SIGNED.strings.memo_disclaimer));
  assert.equal(norm(classifyAnalyseError(new ApiError(401, "/x")).message), norm(APP_SIGNED.strings.session_401));
});

test("no source file in the app says a REFER 'means a lawyer must decide' or 'must decide this matter'", () => {
  const walk = (dir: string): string[] =>
    readdirSync(dir, { withFileTypes: true }).flatMap((d) => (d.isDirectory() ? walk(join(dir, d.name)) : [join(dir, d.name)]));
  const src = join(__dirname, "..");
  const files = walk(src).filter((f) => /\.(ts|tsx)$/.test(f) && !/\.spec\.ts$/.test(f));
  assert.ok(files.length > 50);
  for (const f of files) assert.doesNotMatch(readFileSync(f, "utf8"), /means a lawyer must decide|must decide this matter/i, f);
});

test("the coded-error strings (pravrudhi #319) are the signed wording verbatim, from a header that names the note, head and sha256", () => {
  assert.match(CODED.source.head, /^e65e5ffc$/);
  assert.match(CODED.source.file_sha256, /^[0-9a-f]{64}$/);
  for (const [code, text] of Object.entries(CODED_ERROR_TEXT)) assert.equal(norm(text), norm(CODED.strings[code]), code);
  assert.equal(norm(streamErrorText({ type: "error", error: "chat_endpoint_unreachable", detail: "x" })), norm(CODED.strings.chat_endpoint_unreachable));
  const shown = (e: ApiError) => norm(classifyAnalyseError(e).message);
  assert.equal(shown(new ApiError(503, "/x", { code: "agent_at_capacity" })), norm(CODED.strings.agent_at_capacity));
  assert.equal(shown(new ApiError(503, "/x", { code: "agent_unavailable" })), norm(CODED.strings.agent_unavailable));
  // every signed coded string is either surfaced by the app or in the named allow-list
  for (const code of Object.keys(CODED.strings)) assert.ok(code in CODED_ERROR_TEXT || code in NO_APP_SURFACE_FOLLOW_UP, `${code} has neither an app surface nor an allow-list entry`);
});

test("the citation check's error strings are the signed wording verbatim, and the page shows them", () => {
  // R1's later replacement wins where it exists; the superseded wording is kept in the amendments fixture and must differ from the live one.
  const signed = (code: string): string => AMEND.strings[code] ?? GAP.strings[code];
  for (const [code, text] of Object.entries(CITATION_ERROR_TEXT)) assert.equal(norm(text), norm(signed(code)), code);
  assert.equal(norm(AMEND.supersedes.verify_at_capacity), norm(GAP.strings.verify_at_capacity));
  assert.notEqual(norm(CITATION_ERROR_TEXT.verify_at_capacity), norm(GAP.strings.verify_at_capacity));
  assert.doesNotMatch(CITATION_ERROR_TEXT.verify_at_capacity, /Retry-After/);
  const shown = (e: ApiError) => norm(classifyVerifyError(e).message);
  assert.equal(shown(new ApiError(503, "/x", { code: "verify_timeout" })), norm(GAP.strings.verify_timeout));
  assert.equal(shown(new ApiError(503, "/x", { code: "verify_at_capacity" })), norm(AMEND.strings.verify_at_capacity));
  assert.equal(shown(new ApiError(503, "/x", { code: "citation_index_unavailable" })), norm(GAP.strings.citation_index_unavailable));
});
